name: artivation
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  http: ^0.12.0+1
  flutter_image: ^1.0.0
  url_launcher: ^4.0.3
  font_awesome_flutter: ^8.2.0
  shared_preferences: ^0.4.3
  rxdart: ^0.20.0
  liquid_pull_to_refresh: ^1.0.2
  flutter_rating: ^0.0.2
  intl: ^0.15.7
  flutter_launcher_icons: ^0.7.0
  badges: ^0.0.6
  hidden_drawer_menu: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"


flutter:

  uses-material-design: true

  assets:
      - assets/kalimwenjuma.jpg
      - assets/robbyn.jpg
      - assets/transparent.png
      - assets/saida.jpg
      - assets/saida.jpeg
      - assets/matty.jpeg
      - assets/jimmy.jpeg
      - assets/henry.jpeg
      - assets/img/animals/animal1.jpeg
      - assets/img/animals/animal2.jpeg
      - assets/img/animals/animal3.jpeg
      - assets/img/animals/animal4.jpeg
      - assets/img/animals/animal5.jpeg
      - assets/img/animals/animal6.jpeg
      - assets/img/animals/animal7.jpeg
      - assets/img/beaches/beach1.jpeg
      - assets/img/beaches/beach2.jpeg
      - assets/img/beaches/beach3.jpeg
      - assets/img/beaches/beach4.jpeg
      - assets/img/beaches/beach5.jpeg
      - assets/img/cartoon/cartoon1.jpeg
      - assets/img/cartoon/cartoon2.jpeg
      - assets/img/cartoon/cartoon3.jpeg
      - assets/img/cartoon/cartoon4.jpeg
      - assets/img/cartoon/cartoon5.jpeg
      - assets/img/cartoon/cartoon6.png
      - assets/img/flower/flower1.jpeg
      - assets/img/flower/flower2.jpeg
      - assets/img/flower/flower3.jpeg
      - assets/img/flower/flower4.jpeg
      - assets/img/flower/flower5.jpeg
      - assets/img/flower/flower6.jpeg
      - assets/img/flower/flower7.png
      - assets/img/grafitti/grafitti1.jpg
      - assets/img/grafitti/grafitti2.jpg
      - assets/img/grafitti/grafitti3.jpg
      - assets/img/grafitti/grafitti4.jpeg
      - assets/img/grafitti/grafitti5.jpeg
      - assets/img/grafitti/grafitti6.jpeg
      - assets/img/grafitti/grafitti7.jpg
      - assets/img/grafitti/grafitti8.jpg
      - assets/img/house/house1.jpeg
      - assets/img/house/house2.jpeg
      - assets/img/house/house3.jpeg
      - assets/img/house/house4.jpeg
      - assets/img/house/house5.jpeg
      - assets/img/house/house6.jpeg
      - assets/img/house/house7.jpeg
      - assets/img/insects/insect1.jpg
      - assets/img/insects/insect2.jpg
      - assets/img/insects/insect3.jpg
      - assets/img/insects/insect4.jpeg
      - assets/img/love/love1.jpg
      - assets/img/love/love2.jpg
      - assets/img/love/love3.jpeg
      - assets/img/love/love4.jpeg
      - assets/img/love/love5.jpeg
      - assets/img/love/love6.jpeg
      - assets/img/love/love7.jpeg
      - assets/img/love/love8.jpeg
      - assets/img/love/love9.jpeg
      - assets/img/love/love10.jpeg
      - assets/img/love/love11.jpeg
      - assets/img/love/love12.jpeg
      - assets/img/nature/nature1.jpeg
      - assets/img/nature/nature2.jpeg
      - assets/img/nature/nature3.jpg
      - assets/img/nature/nature4.jpeg
      - assets/img/people/people1.jpeg
      - assets/img/people/people2.jpeg
      - assets/img/people/people3.jpeg
      - assets/img/trees/tree1.jpg
      - assets/img/trees/tree2.jpg
      - assets/img/trees/tree3.jpeg
      - assets/dark_grunge_bk.jpg
  
    








      
      




  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf