import 'package:artivation/models/piece.dart';
import 'package:artivation/utils/enum.dart';

class PieceRepository {
  static List<Piece> loadPieces(Category category) {
    List<Piece> allPieces = <Piece>[
      Piece(
        id: 0,
        artistId: 2,
        cartStatus: false,
        category: Category.animals,
        desc: null,
        isFavorite: false,
        likeCounts: 14,
        price: 20000,
        rate: 0,
        image: 'assets/img/animals/animal1.jpeg',
        size: '40 X 40 cm',
        title: 'Dynaso',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 1,
        artistId: 3,
        cartStatus: false,
        category: Category.all,
        desc: null,
        isFavorite: false,
        likeCounts: 23,
        price: 12000,
        rate: 0,
        image: 'assets/img/animals/animal2.jpeg',
        size: '40 X 40 cm',
        title: 'Horse',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 2,
        artistId: 2,
        cartStatus: false,
        category: Category.all,
        desc: null,
        isFavorite: false,
        likeCounts: 10,
        price: 12000,
        rate: 0,
        image: 'assets/img/animals/animal3.jpeg',
        size: '40 X 40 cm',
        title: 'Animal Kingdom',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 3,
        artistId: 2,
        cartStatus: false,
        category: Category.animals,
        desc: null,
        isFavorite: false,
        likeCounts: 0,
        price: 12000,
        rate: 0,
        image: 'assets/img/animals/animal4.jpeg',
        size: '40 X 40 cm',
        title: 'Wolf',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 4,
        artistId: 1,
        cartStatus: false,
        category: Category.animals,
        desc: null,
        isFavorite: false,
        likeCounts: 0,
        price: 12000,
        rate: 0,
        image: 'assets/img/animals/animal5.jpeg',
        size: '40 X 40 cm',
        title: 'Simba',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 5,
        artistId: 5,
        cartStatus: false,
        category: Category.animals,
        desc: null,
        isFavorite: false,
        likeCounts: 40,
        price: 12000,
        rate: 0,
        image: 'assets/img/animals/animal6.jpeg',
        size: '40 X 40 cm',
        title: 'An old Soul',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 6,
        artistId: 4,
        cartStatus: false,
        category: Category.animals,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/animals/animal7.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 7,
        artistId: 6,
        cartStatus: false,
        category: Category.beaches,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/beaches/beach1.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 8,
        artistId: 3,
        cartStatus: false,
        category: Category.beaches,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/beaches/beach2.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 9,
        artistId: 2,
        cartStatus: false,
        category: Category.beaches,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/beaches/beach3.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 10,
        artistId: 1,
        cartStatus: false,
        category: Category.beaches,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/beaches/beach4.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 11,
        artistId: 2,
        cartStatus: false,
        category: Category.beaches,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/beaches/beach5.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 12,
        artistId: 3,
        cartStatus: false,
        category: Category.cartoons,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/cartoon/cartoon1.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 13,
        artistId: 2,
        cartStatus: false,
        category: Category.cartoons,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/cartoon/cartoon2.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 14,
        artistId: 1,
        cartStatus: false,
        category: Category.cartoons,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/cartoon/cartoon3.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 15,
        artistId: 2,
        cartStatus: false,
        category: Category.cartoons,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/cartoon/cartoon4.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 16,
        artistId: 3,
        cartStatus: false,
        category: Category.cartoons,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/cartoon/cartoon5.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 17,
        artistId: 5,
        cartStatus: false,
        category: Category.cartoons,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/cartoon/cartoon6.png',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 18,
        artistId: 6,
        cartStatus: false,
        category: Category.flowers,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/flower/flower1.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 19,
        artistId: 7,
        cartStatus: false,
        category: Category.flowers,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/flower/flower2.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 20,
        artistId: 7,
        cartStatus: false,
        category: Category.flowers,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/flower/flower3.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 21,
        artistId: 7,
        cartStatus: false,
        category: Category.flowers,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/flower/flower4.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 22,
        artistId: 7,
        cartStatus: false,
        category: Category.flowers,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/flower/flower5.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 23,
        artistId: 1,
        cartStatus: false,
        category: Category.flowers,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/flower/flower6.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 24,
        artistId: 2,
        cartStatus: false,
        category: Category.flowers,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/flower/flower7.png',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 25,
        artistId: 2,
        cartStatus: false,
        category: Category.grafitti,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/grafitti/grafitti1.jpg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 26,
        artistId: 2,
        cartStatus: false,
        category: Category.grafitti,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/grafitti/grafitti2.jpg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 27,
        artistId: 2,
        cartStatus: false,
        category: Category.grafitti,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/grafitti/grafitti3.jpg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 28,
        artistId: 4,
        cartStatus: false,
        category: Category.grafitti,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/grafitti/grafitti4.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 29,
        artistId: 4,
        cartStatus: false,
        category: Category.grafitti,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/grafitti/grafitti6.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 30,
        artistId: 3,
        cartStatus: false,
        category: Category.grafitti,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/grafitti/grafitti7.jpg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 31,
        artistId: 4,
        cartStatus: false,
        category: Category.grafitti,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/grafitti/grafitti8.jpg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 32,
        artistId: 3,
        cartStatus: false,
        category: Category.grafitti,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/grafitti/grafitti5.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 33,
        artistId: 7,
        cartStatus: false,
        category: Category.house,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/house/house1.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 34,
        artistId: 6,
        cartStatus: false,
        category: Category.house,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/house/house2.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 35,
        artistId: 5,
        cartStatus: false,
        category: Category.house,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/house/house3.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 36,
        artistId: 4,
        cartStatus: false,
        category: Category.house,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/house/house4.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 37,
        artistId: 1,
        cartStatus: false,
        category: Category.house,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/house/house5.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 38,
        artistId: 1,
        cartStatus: false,
        category: Category.house,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/house/house6.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 39,
        artistId: 2,
        cartStatus: false,
        category: Category.house,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/house/house7.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 40,
        artistId: 1,
        cartStatus: false,
        category: Category.insects,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/insects/insect1.jpg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 41,
        artistId: 2,
        cartStatus: false,
        category: Category.insects,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/insects/insect2.jpg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 42,
        artistId: 2,
        cartStatus: false,
        category: Category.insects,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/insects/insect3.jpg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 43,
        artistId: 4,
        cartStatus: false,
        category: Category.insects,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/insects/insect4.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 44,
        artistId: 3,
        cartStatus: false,
        category: Category.love,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/love/love1.jpg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 45,
        artistId: 2,
        cartStatus: false,
        category: Category.love,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/love/love2.jpg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 46,
        artistId: 2,
        cartStatus: false,
        category: Category.love,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/love/love3.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 47,
        artistId: 1,
        cartStatus: false,
        category: Category.love,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/love/love4.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 48,
        artistId: 5,
        cartStatus: false,
        category: Category.love,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/love/love5.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 49,
        artistId: 5,
        cartStatus: false,
        category: Category.love,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/love/love6.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 50,
        artistId: 4,
        cartStatus: false,
        category: Category.love,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/love/love7.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 51,
        artistId: 2,
        cartStatus: false,
        category: Category.love,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/love/love8.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 52,
        artistId: 3,
        cartStatus: false,
        category: Category.love,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/love/love9.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 53,
        artistId: 1,
        cartStatus: false,
        category: Category.love,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/love/love10.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 54,
        artistId: 2,
        cartStatus: false,
        category: Category.love,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/love/love11.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 55,
        artistId: 4,
        cartStatus: false,
        category: Category.love,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/love/love12.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 56,
        artistId: 3,
        cartStatus: false,
        category: Category.nature,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/nature/nature1.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 57,
        artistId: 2,
        cartStatus: false,
        category: Category.nature,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/nature/nature2.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 58,
        artistId: 3,
        cartStatus: false,
        category: Category.nature,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/nature/nature3.jpg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 59,
        artistId: 2,
        cartStatus: false,
        category: Category.nature,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/nature/nature4.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 60,
        artistId: 5,
        cartStatus: false,
        category: Category.people,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/people/people1.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 61,
        artistId: 4,
        cartStatus: false,
        category: Category.people,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/people/people2.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 62,
        artistId: 4,
        cartStatus: false,
        category: Category.people,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/people/people3.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 63,
        artistId: 3,
        cartStatus: false,
        category: Category.trees,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/trees/tree1.jpg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 64,
        artistId: 3,
        cartStatus: false,
        category: Category.trees,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/trees/tree2.jpg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
      Piece(
        id: 65,
        artistId: 1,
        cartStatus: false,
        category: Category.trees,
        desc: null,
        isFavorite: false,
        likeCounts: 90,
        price: 112000,
        rate: 0,
        image: 'assets/img/trees/tree3.jpeg',
        size: '40 X 40 cm',
        title: 'Baby Elephant',
        favoriteList: <int>[1, 2, 3, 4, 5, 6],
      ),
    ];
    return allPieces.toList();
  }
}
